services:
  - type: web
    name: traana-disaster-response
    env: node
    plan: free
    buildCommand: npm run postinstall && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
